# Generated by Django 5.0.1 on 2024-01-28 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название ингредиента")),
                ("measurement_unit", models.TextField(max_length=200, verbose_name="единицы измерения")),
                (
                    "cooked_times",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество раз приготовлен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.CreateModel(
            name="IngredientInRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество ингредиентов",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ingredient",
                        verbose_name="ингредиенты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент-рецепт",
                "verbose_name_plural": "Ингредиент-рецепт",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.TextField(help_text="Введите название", max_length=200, verbose_name="Название"),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        help_text="Ингредиент из таблицы Ingredient",
                        related_name="recipes",
                        through="api.IngredientInRecipe",
                        to="api.ingredient",
                        verbose_name="ингредиенты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепты",
                "verbose_name_plural": "Рецепты",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="ingredientinrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_list",
                to="api.recipe",
                verbose_name="рецепты",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientinrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="Не должно быть одинаковых ингредиентов!"
            ),
        ),
    ]
